# Generated by Django 5.1 on 2024-09-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras_base',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
