# Generated by Django 5.1 on 2024-10-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_usuario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
    ]
