# Generated by Django 5.1 on 2024-10-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Asistente', 'Asistente'), ('Cajero', 'Cajero'), ('Atención al cliente', 'Atención al cliente')], max_length=50),
        ),
    ]
