# Generated by Django 5.1 on 2024-10-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
