# Generated by Django 5.1 on 2024-10-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_factura_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
