# Generated by Django 5.1 on 2024-10-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_remove_factura_empleado_delete_detallefactura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.camaras_base')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(related_name='facturas', through='libreria.ProductoFactura', to='libreria.camaras_base'),
        ),
    ]
