# Generated by Django 5.1 on 2024-10-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_factura_productofactura_factura_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras_base',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio de oferta'),
        ),
    ]
