# Generated by Django 5.1 on 2024-10-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_camaras_base_precio_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camaras_base',
            old_name='precio_oferta',
            new_name='precio_compra',
        ),
    ]
