# Generated by Django 5.1 on 2024-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_rename_precio_oferta_camaras_base_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
