# Generated by Django 5.1 on 2024-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_alter_factura_total_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras_base',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='camaras_base',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor comprado'),
        ),
    ]
