# Generated by Django 5.1.7 on 2025-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_alter_camaras_base_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras_base',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
