# Generated by Django 5.1.7 on 2025-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_alter_camaras_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras_base',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
